(function(){
  function rows(){const q=(assetSearch.value||'').toLowerCase(), tp=assetType.value, st=assetStatus.value;return window.storage.list('assets').filter(x=>(!q||[x.name,(x.tags||[]).join(' '),x.created_by].join(' ').toLowerCase().includes(q))&&(!tp||x.type===tp)&&(!st||x.status===st));}
  function render(){assetRows.innerHTML=rows().map(x=>`<tr><td><input type="checkbox" data-id="${x.id}"></td><td>${x.drive_link?`<a class="link" href="${window.ui.esc(x.drive_link)}" target="_blank">${window.ui.esc(x.name)}</a>`:window.ui.esc(x.name)}</td><td>${window.ui.esc(x.type)}</td><td>${(x.tags||[]).map(t=>window.ui.pill(t,'blue')).join(' ')}</td><td>${window.ui.esc(x.created_by)}</td><td>${window.ui.pill(x.status,window.ui.statusType(x.status))}</td><td>${(x.used_in||[]).length}</td><td><button class="btn small" data-detail="${x.id}">Detail</button> <button class="btn small" data-edit="${x.id}">Edit</button> <button class="btn small danger" data-del="${x.id}">Del</button></td></tr>`).join('')||`<tr><td colspan="8">${window.ui.empty()}</td></tr>`;bind();}
  function form(x={}){return `<div class="form-grid"><label class="full">Nama Asset<input data-field="name" value="${window.ui.esc(x.name)}"></label><label>Tipe<select data-field="type"><option>Poster Design</option><option>Video Master</option><option>Caption Template</option><option>Thumbnail</option><option>Logo Variant</option><option>Lain</option></select></label><label>Status<select data-field="status"><option>Active</option><option>Archived</option></select></label><label>Uploaded At<input type="date" data-field="uploaded_at" value="${x.uploaded_at||window.storage.todayISO()}"></label><label>Created By<input data-field="created_by" value="${window.ui.esc(x.created_by)}"></label><label class="full">Google Drive Link<input data-field="drive_link" value="${window.ui.esc(x.drive_link)}"></label><label class="full">Tags (pisah koma)<input data-field="tags_text" value="${window.ui.esc((x.tags||[]).join(', '))}"></label><label class="full">Notes<textarea data-field="notes">${window.ui.esc(x.notes)}</textarea></label></div>`;}
  function open(id){const item=id?window.storage.get('assets',id):{status:'Active',type:'Poster Design'};const m=window.ui.modal(id?'Edit Asset':'Tambah Asset',form(item),'<button class="btn" data-close>Cancel</button><button class="btn primary" id="save">Save</button>');window.ui.setFormData(m.node,Object.assign({},item,{tags_text:(item.tags||[]).join(', ')}));m.node.querySelector('#save').onclick=()=>{const d=window.ui.formData(m.node);d.tags=String(d.tags_text||'').split(',').map(x=>x.trim()).filter(Boolean);delete d.tags_text;id?window.storage.update('assets',id,d):window.storage.add('assets',d);m.close();render();};}
  function detail(id){const x=window.storage.get('assets',id);const body=`<p><b>${window.ui.esc(x.name)}</b></p><p>${x.drive_link?`<a class="link" href="${window.ui.esc(x.drive_link)}" target="_blank">Open Drive</a>`:'-'}</p><h3>Used In</h3>${(x.used_in||[]).length?`<table class="data-table"><tbody>${x.used_in.map(u=>`<tr><td>${window.ui.esc(u.channel)}</td><td class="mono">${window.ui.esc(u.ref_id)}</td></tr>`).join('')}</tbody></table>`:window.ui.empty('Belum dipakai.')}`;window.ui.modal('Detail Asset',body);}
  function bind(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(b.dataset.edit));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete asset?')){window.storage.remove('assets',b.dataset.del);render();}});}
  function init(){['assetSearch','assetType','assetStatus'].forEach(id=>document.getElementById(id).addEventListener('input',render));addAssetBtn.onclick=()=>open();deleteSelectedAssets.onclick=()=>{const ids=window.ui.selectedIds('#assetRows');if(ids.length&&confirm('Delete selected?')){window.storage.bulkRemove('assets',ids);render();}};render();}
  window.AssetsPage={init};
})();
