(function(){
  let charts=[]; function kill(){charts.forEach(c=>c.destroy?.()); charts=[];}
  function totalSpend(){return Object.values(window.attribution.spendByChannel()).reduce((a,b)=>a+b,0);}
  function renderKpis(){const leads=window.storage.list('leads').length; const deals=window.storage.list('deals').length; const spend=totalSpend(); const cpl=leads?spend/leads:0; const conv=leads?deals/leads*100:0; const top=Object.entries(window.attribution.leadsByChannel()).sort((a,b)=>b[1]-a[1])[0];
    document.getElementById('kpiGrid').innerHTML=[[window.i18n?.t?.('suite_dashboard.leads','Total Leads') || 'Total Leads',leads],[window.i18n?.t?.('suite_dashboard.active_deals','Total Deals') || 'Total Deals',deals],[window.i18n?.t?.('suite_dashboard.spend','Marketing Spend') || 'Marketing Spend',window.ui.money(spend)],[window.i18n?.t?.('suite_dashboard.cpl','Cost / Lead') || 'Cost / Lead',window.ui.money(cpl)],['Top Channel',top?window.attribution.sourceName(top[0]):'-']].map(([l,v])=>`<div class="kpi-card"><span>${window.ui.esc(l)}</span><strong>${v}</strong></div>`).join(''); }
  function renderCharts(){kill(); if(!window.Chart)return; const leads=window.attribution.leadsByChannel(); const spend=window.attribution.spendByChannel(); const c1=document.getElementById('leadsChannelChart'), c2=document.getElementById('spendChannelChart'); if(c1)charts.push(new Chart(c1,{type:'doughnut',data:{labels:Object.keys(leads).map(window.attribution.sourceName),datasets:[{data:Object.values(leads)}]},options:{plugins:{legend:{position:'bottom'}}}})); if(c2)charts.push(new Chart(c2,{type:'bar',data:{labels:Object.keys(spend).map(window.attribution.sourceName),datasets:[{label:'Spend',data:Object.values(spend)}]},options:{plugins:{legend:{display:false}}}})); }
  function renderRecent(){const rows=window.storage.list('leads').slice(-6).reverse(); document.getElementById('recentLeads').innerHTML=rows.length?rows.map(l=>`<div class="list-item"><strong>${window.ui.esc(l.customer_name||l.name||'-')}</strong><small>${window.ui.esc(window.attribution.sourceName(window.attribution.sourceOfLead(l)))} · ${window.ui.esc(window.attribution.campaignNameFromLead(l))}</small></div>`).join(''):window.ui.empty(window.i18n?.t?.('suite_dashboard.empty','Belum ada leads.') || 'Belum ada leads.');}
  function renderTop(){const leads=window.attribution.leadsByChannel(); const deals=window.attribution.dealsByChannel(); const spend=window.attribution.spendByChannel(); const rows=Object.keys(Object.assign({},leads,deals,spend)).map(c=>({c,leads:leads[c]||0,deals:deals[c]||0,spend:spend[c]||0})).sort((a,b)=>b.leads-a.leads).slice(0,5); document.getElementById('topCampaigns').innerHTML=rows.length?rows.map(r=>`<div class="list-item"><strong>${window.ui.esc(window.attribution.sourceName(r.c))}</strong><small>${r.leads} leads · ${r.deals} deals · ${window.ui.money(r.spend)}</small></div>`).join(''):window.ui.empty();}
  function renderPending(){const pending=[]; window.storage.list('offline_batches').forEach(x=>{if(!x.finance_journaled&&(Number(x.print_cost||0)+Number(x.distribution_cost||0)>0))pending.push(['Offline',x.id,Number(x.print_cost||0)+Number(x.distribution_cost||0)]);}); window.storage.list('tiktok_ads').forEach(x=>{if(!x.finance_journaled&&Number(x.budget_total||0)>0)pending.push(['TikTok Ads',x.id,Number(x.budget_total||0)]);}); window.storage.list('meta_campaigns').forEach(x=>{if(!x.finance_journaled&&Number(x.budget_total||0)>0)pending.push(['Meta Ads',x.id,Number(x.budget_total||0)]);}); window.storage.list('partner_payments').forEach(x=>{if(x.status==='Pending')pending.push(['Partner Payment',x.id,Number(x.amount||0)]);}); document.getElementById('pendingFinancePosts').innerHTML=pending.length?pending.slice(0,6).map(p=>`<div class="list-item"><strong>${window.ui.esc(p[0])}</strong><small>${window.ui.esc(p[1])} · ${window.ui.money(p[2])}</small></div>`).join(''):window.ui.empty(window.i18n?.t?.('suite_dashboard.empty','Tidak ada pending finance post.') || 'Tidak ada pending finance post.');}
  function init(){renderKpis();renderCharts();renderRecent();renderTop();renderPending();}
  window.MarketingDashboard={init};
})();
