(function(){
  function ensureCoa(code,name_id,name_zh,type){const coa=window.storage.list('coa'); if(!coa.find(a=>a.code===code)){coa.push({id:'acc_'+code,code,name_id,name_zh,type,normal_balance:type==='asset'?'debit':'debit',opening_balance:0,is_active:true,created_at:new Date().toISOString()}); window.storage.write('coa',coa);} }
  function nextJournalNo(){const rows=window.storage.list('journal'); const max=rows.map(j=>Number(String(j.journal_number||'').replace(/\D/g,''))).filter(Boolean).sort((a,b)=>b-a)[0]||0; return 'JU-'+String(max+1).padStart(3,'0');}
  function account(code){return window.storage.list('coa').find(a=>a.code===code)||{id:'acc_'+code,code,name_id:code,name_zh:code};}
  function posted(ref){const links=window.storage.list('marketing_journal_links');return !!links[ref];}
  function markPosted(ref,je){const links=window.storage.list('marketing_journal_links');links[ref]=je;window.storage.write('marketing_journal_links',links);}
  function postMarketingExpense({date,description,amount,ref,proof_link,client_name}){ if(!amount||amount<=0) throw new Error('Amount invalid'); if(posted(ref)) return {skipped:true, journal_entry_id:posted(ref)}; ensureCoa('11000','Kas & Bank','现金及银行','asset'); ensureCoa('52000','Biaya Marketing','营销费用','expense'); const dr=account('52000'), cr=account('11000'); const entry={id:window.storage.genId('je'),journal_number:nextJournalNo(),date:date||window.storage.todayISO(),description,client_name:client_name||'',doc_number:ref,proof_link:proof_link||'',source:'marketing',cf_ref:null,deal_id:null,lines:[{account_id:dr.id,account_code:dr.code,account_name_snapshot:dr.name_id,debit:Number(amount),credit:0},{account_id:cr.id,account_code:cr.code,account_name_snapshot:cr.name_id,debit:0,credit:Number(amount)}],created_at:new Date().toISOString(),created_by_role:window.storage.getSettings().role}; window.storage.add('journal',entry); markPosted(ref,entry.id); return {journal_entry_id:entry.id}; }
  window.financeBridge={postMarketingExpense,posted};
})();
