(function(){
  function lastMetric(id){return window.storage.list('meta_metrics').filter(m=>m.campaign_id===id).sort((a,b)=>String(b.snapshot_date).localeCompare(String(a.snapshot_date)))[0]||{};}
  function rows(){const q=(metaSearch.value||'').toLowerCase(), pl=metaPlatform.value, st=metaStatus.value;return window.storage.list('meta_campaigns').filter(x=>(!q||String(x.campaign_name||'').toLowerCase().includes(q))&&(!pl||x.platform===pl)&&(!st||x.status===st));}
  function render(){metaRows.innerHTML=rows().map(x=>{const m=lastMetric(x.id);return `<tr><td><input type="checkbox" data-id="${x.id}"></td><td>${window.ui.esc(x.campaign_name)}</td><td>${window.ui.esc(x.platform)}</td><td>${x.start_date||''} - ${x.end_date||''}</td><td>${window.ui.esc(x.objective)}</td><td>${window.ui.money(x.budget_total)}</td><td>${window.ui.pill(x.status,window.ui.statusType(x.status))}</td><td>${window.ui.money(m.spend_to_date)}</td><td>${Number(m.leads||m.messages_received||0)}</td><td><button class="btn small" data-met="${x.id}">Metric</button> <button class="btn small accent" data-post="${x.id}">Post</button> <button class="btn small" data-edit="${x.id}">Edit</button> <button class="btn small danger" data-del="${x.id}">Del</button></td></tr>`}).join('')||`<tr><td colspan="10">${window.ui.empty()}</td></tr>`;bind();}
  function form(x={}){return `<div class="form-grid"><label class="full">Campaign Name<input data-field="campaign_name" value="${window.ui.esc(x.campaign_name)}"></label><label>Platform<select data-field="platform"><option>Facebook</option><option>Instagram</option><option>Both</option></select></label><label>Objective<select data-field="objective"><option>Reach</option><option>Traffic</option><option>Messages</option><option>Leads</option><option>Conversions</option></select></label><label>Start<input type="date" data-field="start_date" value="${x.start_date||window.storage.todayISO()}"></label><label>End<input type="date" data-field="end_date" value="${x.end_date||''}"></label><label>Budget Total<input type="number" data-field="budget_total" value="${x.budget_total||0}"></label><label>Budget Harian<input type="number" data-field="budget_daily" value="${x.budget_daily||0}"></label><label>Status<select data-field="status"><option>Active</option><option>Paused</option><option>Ended</option></select></label><label class="full">Creative Link<input data-field="creative_link" value="${window.ui.esc(x.creative_link)}"></label><label class="full">Target Audience Notes<textarea data-field="target_notes">${window.ui.esc(x.target_notes)}</textarea></label></div>`;}
  function metricForm(id){return `<div class="form-grid"><input type="hidden" data-field="campaign_id" value="${id}"><label>Snapshot Date<input type="date" data-field="snapshot_date" value="${window.storage.todayISO()}"></label><label>Source<select data-field="source"><option>manual</option><option>csv_import_meta_business_suite</option></select></label><label>Reach<input type="number" data-field="reach"></label><label>Impressions<input type="number" data-field="impressions"></label><label>Clicks<input type="number" data-field="clicks"></label><label>CTR %<input type="number" step="0.01" data-field="ctr"></label><label>CPC<input type="number" data-field="cpc"></label><label>CPM<input type="number" data-field="cpm"></label><label>Messages<input type="number" data-field="messages_received"></label><label>Leads<input type="number" data-field="leads"></label><label>Total Spend<input type="number" data-field="spend_to_date"></label></div>`;}
  function open(id){const item=id?window.storage.get('meta_campaigns',id):{platform:'Both',objective:'Messages',status:'Active'};const m=window.ui.modal(id?'Edit Meta Campaign':'Tambah Meta Campaign',form(item),'<button class="btn" data-close>Cancel</button><button class="btn primary" id="save">Save</button>');window.ui.setFormData(m.node,item);m.node.querySelector('#save').onclick=()=>{const d=window.ui.formData(m.node);id?window.storage.update('meta_campaigns',id,d):window.storage.add('meta_campaigns',d);m.close();render();};}
  function openMetric(id){const m=window.ui.modal('Tambah Meta Metric',metricForm(id),'<button class="btn" data-close>Cancel</button><button class="btn primary" id="save">Save</button>');m.node.querySelector('#save').onclick=()=>{window.storage.add('meta_metrics',window.ui.formData(m.node));m.close();render();};}
  function post(id){const x=window.storage.get('meta_campaigns',id);try{const je=window.financeBridge.postMarketingExpense({date:x.start_date,description:`Biaya Meta Ads ${x.campaign_name}`,amount:x.budget_total,ref:`MKT-META-${x.id}`,proof_link:x.creative_link});window.storage.update('meta_campaigns',id,{finance_journaled:true,journal_entry_id:je.journal_entry_id});window.ui.toast('Journal posted');render();}catch(e){window.ui.toast(e.message);}}
  function importCsv(){const m=window.ui.modal('Import Meta CSV','<p>Header: campaign_id,snapshot_date,reach,impressions,clicks,ctr,cpc,cpm,messages_received,leads,spend_to_date</p><textarea id="csv" style="width:100%;min-height:220px"></textarea>','<button class="btn" data-close>Cancel</button><button class="btn primary" id="doImport">Import</button>');m.node.querySelector('#doImport').onclick=()=>{const rows=window.ui.parseCsv(m.node.querySelector('#csv').value);rows.forEach(r=>window.storage.add('meta_metrics',Object.assign({source:'csv_import_meta_business_suite'},r)));window.ui.toast(`${rows.length} rows imported`);m.close();render();};}
  function bind(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete campaign?')){window.storage.remove('meta_campaigns',b.dataset.del);render();}});document.querySelectorAll('[data-met]').forEach(b=>b.onclick=()=>openMetric(b.dataset.met));document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>post(b.dataset.post));}
  function init(){['metaSearch','metaPlatform','metaStatus'].forEach(id=>document.getElementById(id).addEventListener('input',render));addMetaBtn.onclick=()=>open();importMetaCsv.onclick=importCsv;deleteSelectedMeta.onclick=()=>{const ids=window.ui.selectedIds('#metaRows');if(ids.length&&confirm('Delete selected?')){window.storage.bulkRemove('meta_campaigns',ids);render();}};render();}
  window.MetaPage={init};
})();
