(function(){
  function cost(x){return Number(x.print_cost||0)+Number(x.distribution_cost||0);} function rows(){const q=(document.getElementById('offlineSearch').value||'').toLowerCase(), st=document.getElementById('offlineStatus').value, zone=(document.getElementById('offlineZone').value||'').toLowerCase(); return window.storage.list('offline_batches').filter(x=>(!q||[x.location,x.zone,x.tracking_code,x.pic].join(' ').toLowerCase().includes(q))&&(!st||x.status===st)&&(!zone||String(x.zone||'').toLowerCase().includes(zone))).sort((a,b)=>String(b.spread_date).localeCompare(String(a.spread_date)));}
  function render(){document.getElementById('offlineRows').innerHTML=rows().map(x=>`<tr><td><input type="checkbox" data-id="${x.id}"></td><td>${x.spread_date||''}</td><td>${window.ui.esc(x.location)}</td><td>${window.ui.esc(x.zone)}</td><td>${x.poster_qty||0}</td><td class="mono">${window.ui.esc(x.tracking_code)}</td><td>${window.ui.money(cost(x))}</td><td>${window.ui.esc(x.pic)}</td><td>${window.ui.pill(x.status,window.ui.statusType(x.status))}</td><td>${x.finance_journaled?window.ui.pill('Posted','green'):window.ui.pill('Pending','yellow')}</td><td><button class="btn small" data-edit="${x.id}">Edit</button> <button class="btn small accent" data-post="${x.id}">Post</button> <button class="btn small danger" data-del="${x.id}">Del</button></td></tr>`).join('')||`<tr><td colspan="11">${window.ui.empty()}</td></tr>`; bindRow();}
  function form(item={}){return `<div class="form-grid" id="offlineForm"><label>Tanggal Sebar<input type="date" data-field="spread_date" value="${item.spread_date||window.storage.todayISO()}"></label><label>Zona/Area<input data-field="zone" value="${window.ui.esc(item.zone)}"></label><label class="full">Lokasi Sebar<input data-field="location" value="${window.ui.esc(item.location)}"></label><label>Jumlah Poster<input type="number" data-field="poster_qty" value="${item.poster_qty||0}"></label><label>Kode Tracking<input data-field="tracking_code" value="${window.ui.esc(item.tracking_code)}"></label><label>Biaya Cetak<input type="number" data-field="print_cost" value="${item.print_cost||0}"></label><label>Biaya Distribusi<input type="number" data-field="distribution_cost" value="${item.distribution_cost||0}"></label><label>PIC Penyebar<input data-field="pic" value="${window.ui.esc(item.pic)}"></label><label>Status<select data-field="status"><option>Aktif</option><option>Selesai</option><option>Dicabut</option></select></label><label class="full">Design Asset Link<input data-field="design_asset_link" value="${window.ui.esc(item.design_asset_link)}"></label><label class="full">Foto Bukti Sebar<input data-field="proof_links" value="${window.ui.esc(item.proof_links)}"></label><label class="full">Catatan<textarea data-field="notes">${window.ui.esc(item.notes)}</textarea></label></div>`;}
  function openModal(id){const item=id?window.storage.get('offline_batches',id):{status:'Aktif'}; const m=window.ui.modal(id?'Edit Batch Poster':'Tambah Batch Poster',form(item),'<button class="btn" data-close>Cancel</button><button class="btn primary" id="saveOffline">Save</button>'); window.ui.setFormData(m.node,item); m.node.querySelector('#saveOffline').onclick=()=>{const data=window.ui.formData(m.node); if(!data.spread_date)return window.ui.toast('Tanggal wajib diisi'); id?window.storage.update('offline_batches',id,data):window.storage.add('offline_batches',data); m.close(); render();};}
  function post(id){const x=window.storage.get('offline_batches',id); if(!x)return; try{const je=window.financeBridge.postMarketingExpense({date:x.spread_date,description:`Biaya poster ${x.zone||''} (${x.tracking_code||x.id})`,amount:cost(x),ref:`MKT-OFF-${x.id}`,proof_link:x.proof_links}); window.storage.update('offline_batches',id,{finance_journaled:true,journal_entry_id:je.journal_entry_id}); window.ui.toast(je.skipped?'Sudah pernah dipost':'Journal marketing berhasil dibuat'); render();}catch(e){window.ui.toast(e.message);}}
  function bindRow(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete batch?')){window.storage.remove('offline_batches',b.dataset.del);render();}});document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>post(b.dataset.post));}
  function init(){['offlineSearch','offlineStatus','offlineZone'].forEach(id=>document.getElementById(id).addEventListener('input',render));document.getElementById('addOfflineBtn').onclick=()=>openModal();document.getElementById('deleteSelectedOffline').onclick=()=>{const ids=window.ui.selectedIds('#offlineRows');if(ids.length&&confirm('Delete selected?')){window.storage.bulkRemove('offline_batches',ids);render();}};document.getElementById('selectAllOffline').onchange=e=>document.querySelectorAll('#offlineRows input[data-id]').forEach(c=>c.checked=e.target.checked);render();}
  window.OfflinePage={init};
})();
