(function(){
 const DICT={
  id:{dashboard:'Dashboard',okr:'OKR',kpi:'KPI',employee:'Karyawan',planning:'Planning',reports:'Reports',management_module:'Management Module',settings:'Settings',language:'Bahasa',role:'Role',save_settings:'Save Settings',export_json:'Export JSON',import_json:'Import JSON',reset_all:'Reset All',active_quarter:'Active Quarter',custom_period:'Custom Period',days_remaining:'hari tersisa',okr_score:'OKR Score',operational:'Operational',financial:'Financial',marketing:'Marketing',team:'Team',active_okr:'Active OKR',pinned_kpi:'Pinned KPI',today_tasks:'Today Tasks',alerts:'Alerts',quick_actions:'Quick Actions',new_okr:'+ New OKR',new_task:'+ New Task',new_employee:'+ New Employee',switch_quarter:'Switch Quarter',export_pdf:'Export PDF',quarter:'Quarter',owner:'Owner',category:'Category',status:'Status',progress:'Progress',title:'Title',description:'Description',action:'Action',add:'Tambah',edit:'Edit',delete:'Delete',save:'Save',cancel:'Cancel',close:'Close',search:'Search',filter:'Filter',refresh:'Refresh',use_template:'Use Template',new_kpi:'+ New KPI',pin:'Pin',unpin:'Unpin',target:'Target',current:'Current',metric:'Metric',module:'Module',period:'Period',base_salary:'Gaji Pokok',commission:'Komisi',promotion:'Promosi',performance_review:'Performance Review',tasks:'Tasks',wage_history:'Wage History',joined_date:'Tanggal Join',current_tier:'Current Tier',promote:'Promote',review:'Review',calendar:'Calendar',weekly_review:'Weekly Review',generate_weekly:'Generate Weekly Review',monthly_report:'Monthly Management Report',quarterly_review:'Quarterly OKR Review',team_report:'Team Performance Report',investor_summary:'Investor Summary',module_status:'Module Status',connected:'Connected',not_detected:'Tidak terdeteksi',cash_on_hand:'Cash on Hand',net_income:'Net Income',net_margin:'Net Margin',receivables:'Piutang',lead_this_month:'Lead bulan ini',active_deal:'Deal Aktif',conversion_rate:'Conversion Rate',red_alert:'Alert Merah',spend:'Spend',cpl:'CPL',roi:'ROI',active_employees:'Active Employees',pending_tasks:'Pending Tasks',todays_tasks:'Today Tasks',performance_trend:'Performance Trend',okr_templates:'OKR Templates',metric_catalog:'Metric Catalog',profile:'Profile',info:'Info',notes:'Notes',priority:'Priority',assignee:'Assignee',type:'Type',start:'Start',end:'End',completed:'Completed',pending:'Pending',overdue:'Overdue',done:'Done',print_view:'Print View'},
  zh:{dashboard:'仪表盘',okr:'OKR',kpi:'KPI',employee:'员工',planning:'计划',reports:'报告',management_module:'管理模块',settings:'设置',language:'语言',role:'角色',save_settings:'保存设置',export_json:'导出JSON',import_json:'导入JSON',reset_all:'重置全部',active_quarter:'当前季度',custom_period:'自定义期间',days_remaining:'天剩余',okr_score:'OKR评分',operational:'运营',financial:'财务',marketing:'营销',team:'团队',active_okr:'当前OKR',pinned_kpi:'置顶KPI',today_tasks:'今日任务',alerts:'提醒',quick_actions:'快捷操作',new_okr:'+ 新OKR',new_task:'+ 新任务',new_employee:'+ 新员工',switch_quarter:'切换季度',export_pdf:'导出PDF',quarter:'季度',owner:'负责人',category:'类别',status:'状态',progress:'进度',title:'标题',description:'描述',action:'操作',add:'添加',edit:'编辑',delete:'删除',save:'保存',cancel:'取消',close:'关闭',search:'搜索',filter:'筛选',refresh:'刷新',use_template:'使用模板',new_kpi:'+ 新KPI',pin:'置顶',unpin:'取消置顶',target:'目标',current:'当前',metric:'指标',module:'模块',period:'期间',base_salary:'基本工资',commission:'佣金',promotion:'晋升',performance_review:'绩效复盘',tasks:'任务',wage_history:'工资历史',joined_date:'入职日期',current_tier:'当前级别',promote:'晋升',review:'复盘',calendar:'日历',weekly_review:'每周复盘',generate_weekly:'生成周复盘',monthly_report:'月度管理报告',quarterly_review:'季度OKR复盘',team_report:'团队绩效报告',investor_summary:'投资人摘要',module_status:'模块状态',connected:'已连接',not_detected:'未检测到',cash_on_hand:'可用现金',net_income:'净利润',net_margin:'净利率',receivables:'应收款',lead_this_month:'本月线索',active_deal:'活跃交易',conversion_rate:'转化率',red_alert:'红色预警',spend:'支出',cpl:'获客成本',roi:'投资回报率',active_employees:'在职员工',pending_tasks:'待办任务',todays_tasks:'今日任务',performance_trend:'绩效趋势',okr_templates:'OKR模板',metric_catalog:'指标目录',profile:'档案',info:'资料',notes:'备注',priority:'优先级',assignee:'负责人',type:'类型',start:'开始',end:'结束',completed:'已完成',pending:'待办',overdue:'逾期',done:'完成',print_view:'打印视图'}
 };
 function lang(){ return window.storage?.getSettings()?.language || 'id'; }
 function humanize(key){ return String(key||'').split('.').pop().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
 function t(key,fallback){ return (DICT[lang()]&&DICT[lang()][key]) || DICT.id[key] || fallback || humanize(key); }
 function apply(root=document){ root.querySelectorAll('[data-i18n]').forEach(el=>{ el.textContent=t(el.dataset.i18n); }); root.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{ el.placeholder=t(el.dataset.i18nPlaceholder); }); document.documentElement.lang=lang(); }
 function toggle(){ const next=lang()==='id'?'zh':'id'; window.storage.saveSettings({language:next}); apply(); window.dispatchEvent(new CustomEvent('languagechange',{detail:{language:next}})); }
 window.i18n={t,apply,toggle,lang,DICT};
})();
