(function(){
 let catalog=null;
 const FALLBACK_CATALOG = [];
 async function getMetricCatalog(){ if(catalog)return catalog; try{ const r=await fetch('data/metric-catalog.json',{cache:'no-store'}); if(!r.ok)throw new Error('fetch fail'); catalog=await r.json(); }catch(e){ try{ catalog=JSON.parse(document.getElementById('metricCatalogInline')?.textContent||'[]'); }catch(x){ catalog=FALLBACK_CATALOG; }} return catalog; }
 function rangeFromSource(ds,periodOverride){ const f=ds?.filter||{}; const p=periodOverride || f.period || 'all'; return window.ModuleBridge.periodRange(p); }
 function sum(arr,fn){ return arr.reduce((a,x)=>a+Number(fn?fn(x):x||0),0); }
 function avg(arr,fn){ return arr.length?sum(arr,fn)/arr.length:0; }
 function latestSnapshot(video){ const s=video.snapshots||video.metrics||[]; return s[s.length-1]||{}; }
 function computeFinancial(metric,filter,range){ const lines=window.ModuleBridge.journalLines(range.start_date,range.end_date); const allAsOf=range.end_date||window.QuarterUtil.todayISO(); const rev=()=>sum(lines.filter(l=>String(l.account_code).startsWith('4')),l=>l.credit-l.debit); const exp=()=>sum(lines.filter(l=>String(l.account_code).startsWith('5')),l=>l.debit-l.credit); if(metric==='total_revenue')return rev(); if(metric==='revenue_by_product')return sum(lines.filter(l=>String(l.account_code)===String(filter.account_code||'41100')),l=>l.credit-l.debit); if(metric==='total_expense')return exp(); if(metric==='expense_by_category')return sum(lines.filter(l=>String(l.account_code)===String(filter.account_code||'51000')),l=>l.debit-l.credit); if(metric==='net_income')return rev()-exp(); if(metric==='net_margin_pct')return rev()?((rev()-exp())/rev()*100):0; if(metric==='cash_on_hand')return window.ModuleBridge.accountBalance(['11000','11100','11200'],allAsOf); if(metric==='total_assets')return window.ModuleBridge.accountBalance(['1'],allAsOf); if(metric==='total_liabilities')return -window.ModuleBridge.accountBalance(['2'],allAsOf); if(metric==='total_equity')return -window.ModuleBridge.accountBalance(['3'],allAsOf); if(metric==='outstanding_receivables')return window.ModuleBridge.accountBalance(['12'],allAsOf); if(metric==='roi_investor_pct'){const profit=rev()-exp(); const modal=-window.ModuleBridge.accountBalance(['31000'],allAsOf); return modal?profit/modal*100:0;} if(metric==='commission_paid_total')return sum(window.ModuleBridge.getFinancialData().commissions.filter(c=>c.status==='paid'&&window.ModuleBridge.inRange(c.paid_at||c.created_at,range.start_date,range.end_date)),c=>c.commission_amount); if(metric==='wage_paid_total')return sum(window.ModuleBridge.getFinancialData().wages.filter(w=>w.status==='paid'&&window.ModuleBridge.inRange(w.payment_date||w.created_at,range.start_date,range.end_date)),w=>w.total_wage); return 0; }
 function computeOperational(metric,filter,range){ const {leads,deals}=window.ModuleBridge.getOperationalData(); const L=leads.filter(l=>window.ModuleBridge.inRange(l.created_at||l.date||l.tanggal_masuk,range.start_date,range.end_date)); const D=deals.filter(d=>window.ModuleBridge.inRange(d.created_at||d.start_date||d.due_date,range.start_date,range.end_date)); if(metric==='lead_count')return L.length; if(metric==='lead_count_by_channel')return L.filter(l=>(l.lead_source?.channel||'unknown')===(filter.channel||'unknown')).length; if(metric==='lead_count_by_status')return L.filter(l=>l.status===(filter.status||'Baru')).length; if(metric==='lead_count_by_temperature')return L.filter(l=>l.temperature===(filter.temperature||'Hot')).length; if(metric==='deal_count')return D.length; if(metric==='deal_count_by_status')return D.filter(d=>d.status===(filter.status||'Aktif')).length; if(metric==='deal_count_by_product')return D.filter(d=>d.product_type===(filter.product_type||'JS Lunas 30H')).length; if(metric==='deal_count_by_pic')return D.filter(d=>d.sales_pic_id===(filter.sales_pic_id||'')).length; if(metric==='total_principal_disbursed')return sum(D,d=>d.principal); if(metric==='total_tebus_collected')return sum(D.filter(d=>d.status==='Ditebus'),d=>d.total_tebus); if(metric==='avg_deal_size')return avg(D,d=>d.principal); if(metric==='conversion_rate_lead_to_deal')return L.length?D.length/L.length*100:0; const ms=window.ModuleBridge.getFinancialData().motor_sitaan; if(metric==='motor_sitaan_count')return ms.filter(m=>window.ModuleBridge.inRange(m.date_sitaan||m.created_at,range.start_date,range.end_date)).length; if(metric==='motor_sitaan_sold_count')return ms.filter(m=>m.status==='sold'&&window.ModuleBridge.inRange(m.sale_date,range.start_date,range.end_date)).length; return 0; }
 function computeMarketing(metric,filter,range){ const {videos,campaigns,posters,partners}=window.ModuleBridge.getMarketingData(); const spendPosters=sum(posters.filter(p=>window.ModuleBridge.inRange(p.date||p.tanggal_sebar||p.created_at,range.start_date,range.end_date)),p=>Number(p.print_cost||p.biaya_cetak||0)+Number(p.distribution_cost||p.biaya_distribusi||0)); const spendCampaigns=sum(campaigns.filter(c=>window.ModuleBridge.inRange(c.start_date||c.created_at,range.start_date,range.end_date)),c=>Number(c.total_spend||c.spend||c.budget_total||0)); const spend=spendPosters+spendCampaigns; const {leads,deals}=window.ModuleBridge.getOperationalData(); const mLeads=leads.filter(l=>l.lead_source&&window.ModuleBridge.inRange(l.created_at||l.date,range.start_date,range.end_date)); const mDeals=deals.filter(d=>d.lead_source&&window.ModuleBridge.inRange(d.created_at||d.start_date,range.start_date,range.end_date)); if(metric==='total_marketing_spend')return spend; if(metric==='spend_by_channel')return spend; if(metric==='lead_count_per_channel')return mLeads.filter(l=>l.lead_source.channel===(filter.channel||'tiktok_organic')).length; if(metric==='cpl_overall')return mLeads.length?spend/mLeads.length:0; if(metric==='cpl_by_channel'){const n=mLeads.filter(l=>l.lead_source.channel===(filter.channel||'tiktok_organic')).length; return n?spend/n:0;} if(metric==='cpd_overall')return mDeals.length?spend/mDeals.length:0; if(metric==='marketing_roi_pct'){const rev=sum(mDeals,d=>Number(d.total_tebus||0)-Number(d.principal||0)); return spend?(rev-spend)/spend*100:0;} if(metric==='video_count_published')return videos.filter(v=>v.status==='Published'||v.status==='published').length; if(metric==='total_video_views')return sum(videos,v=>latestSnapshot(v).views||v.views); if(metric==='avg_engagement_rate')return avg(videos,v=>latestSnapshot(v).engagement_rate||0); if(metric==='partner_count_active')return partners.filter(p=>p.status==='Aktif'||p.status==='active').length; if(metric==='commission_partner_paid_total')return sum(partners.flatMap(p=>p.payments||[]).filter(p=>p.status==='Paid'||p.status==='paid'),p=>p.amount); return 0; }
 function computeManagement(metric,filter,range){ if(metric==='employee_count_active')return window.storage.list('employees',e=>e.status==='active').length; if(metric==='task_completion_rate'){const tasks=window.storage.list('tasks').filter(t=>window.ModuleBridge.inRange(t.start_datetime||t.created_at,range.start_date,range.end_date)); const comps=window.storage.list('task_completions').filter(c=>window.ModuleBridge.inRange(c.instance_date||c.completed_at,range.start_date,range.end_date)); return tasks.length?Math.min(100,comps.length/tasks.length*100):0;} if(metric==='okr_completion_avg_pct'){const q=filter.period&&/^\d{4}-Q/.test(filter.period)?filter.period:window.QuarterUtil.getCurrentQuarter(); const okrs=window.storage.list('okrs',o=>o.quarter_key===q); return okrs.length?avg(okrs,o=>computeOKRCompletion(o).completion_pct):0;} return 0; }
 function computeMetric(data_source,periodOverride){ const ds=data_source||{}; const filter=ds.filter||{}; const range=rangeFromSource(ds,periodOverride); let val=0; if(ds.module==='operational')val=computeOperational(ds.metric,filter,range); if(ds.module==='financial')val=computeFinancial(ds.metric,filter,range); if(ds.module==='marketing')val=computeMarketing(ds.metric,filter,range); if(ds.module==='management')val=computeManagement(ds.metric,filter,range); return Number.isFinite(val)?val:0; }
 function computeKRProgress(kr){ const val=kr.type==='manual'?Number(kr.manual_progress_value??kr.current_value??0):computeMetric(kr.data_source); const target=Number(kr.target_value||0); const progress=target?Math.min(100,val/target*100):0; const q=window.storage.get('okrs',kr.okr_id)?.quarter_key||window.QuarterUtil.getCurrentQuarter(); const qp=window.QuarterUtil.getQuarterProgress(q).progress_pct; let status='on_track'; if(progress>=100)status='achieved'; else if(new Date()>new Date(window.QuarterUtil.getQuarterDates(q).end_date+'T23:59:59'))status='missed'; else if(progress>=qp)status='on_track'; else if(progress>=qp-15)status='at_risk'; else status='off_track'; return {current_value:val,progress_pct:progress,status}; }
 function computeOKRCompletion(okr){ const krs=window.storage.list('krs',k=>k.okr_id===okr.id); const totalWeight=sum(krs,k=>Number(k.weight||0))||krs.length||1; const score=sum(krs,k=>computeKRProgress(k).progress_pct*Number(k.weight||1))/totalWeight; return {completion_pct:Math.min(100,score),krs}; }
 function computeKPIValue(kpi){ return computeMetric(kpi.data_source); }
 function snapshotAllKPIs(){ const today=window.QuarterUtil.todayISO(); const snaps=window.storage.list('kpi_snapshots'); window.storage.list('kpis').forEach(k=>{ if(!snaps.some(s=>s.kpi_id===k.id&&s.date===today)){ window.storage.add('kpi_snapshots',{kpi_id:k.id,date:today,value:computeKPIValue(k)}); } }); const all=window.storage.list('kpi_snapshots'); if(all.length>365*20) window.storage.writeJson('kpi_snapshots', all.slice(-365*20)); }
 function getSparklineData(kpi_id,days=30){ return window.storage.list('kpi_snapshots',s=>s.kpi_id===kpi_id).slice(-days); }
 window.MetricEngine={getMetricCatalog,computeMetric,computeKRProgress,computeOKRCompletion,computeKPIValue,snapshotAllKPIs,getSparklineData};
})();
