(function(){
 const T=()=>window.i18n.t;
 function render(){
  const q=document.getElementById('quarterSelect')?.value || window.storage.getSettings().management?.active_quarter || window.QuarterUtil.getCurrentQuarter();
  const root=document.getElementById('okrList'); if(!root)return;
  const okrs=window.storage.list('okrs',o=>o.quarter_key===q&&o.status!=='cancelled');
  root.innerHTML=okrs.length?okrs.map(card).join(''):window.ui.empty('Belum ada OKR');
  root.querySelectorAll('[data-open-okr]').forEach(b=>b.addEventListener('click',()=>openOKR(b.dataset.openOkr)));
  root.querySelectorAll('[data-delete-okr]').forEach(b=>b.addEventListener('click',(e)=>{e.stopPropagation(); if(confirm('Delete OKR?')){ const id=b.dataset.deleteOkr; window.storage.remove('okrs',id); window.storage.list('krs',k=>k.okr_id===id).forEach(k=>window.storage.remove('krs',k.id)); render(); }}));
 }
 function card(o){ const c=window.MetricEngine.computeOKRCompletion(o); const krs=window.storage.list('krs',k=>k.okr_id===o.id); const band=c.completion_pct>=70?'green':c.completion_pct>=30?'yellow':'red'; return `<article class="card okr-card" data-open-okr="${o.id}"><div class="card-head"><div><h2>${window.ui.escapeHtml(window.ui.titleFor(o))}</h2><p>${window.ui.employeeName(o.owner_employee_id)} · ${window.ui.badge(o.category,'neutral')}</p></div><strong class="score ${band}">${Math.round(c.completion_pct)}%</strong></div><p>${window.ui.escapeHtml(window.i18n.lang()==='zh'?(o.description_zh||o.description):(o.description||''))}</p>${window.ui.progressBar(c.completion_pct,band)}<div class="kr-stack">${krs.map(k=>{const p=window.MetricEngine.computeKRProgress(k);return `<div class="kr-row"><span>${window.ui.escapeHtml(window.ui.titleFor(k))}</span><small>${window.ui.fmt(p.current_value,k.unit)} / ${window.ui.fmt(k.target_value,k.unit)} · ${window.ui.badge(p.status,p.status)}</small>${window.ui.progressBar(p.progress_pct,p.status)}</div>`}).join('')}</div><div class="action-row"><button class="btn small" data-open-okr="${o.id}">${window.i18n.t('edit')}</button><button class="btn danger small" data-delete-okr="${o.id}">${window.i18n.t('delete')}</button></div></article>`; }
 function okrForm(o={}){ return `<div class="form-grid"><label>${T()('title')} ID<input data-field="title" value="${window.ui.escapeHtml(o.title||'')}"></label><label>${T()('title')} 中文<input data-field="title_zh" value="${window.ui.escapeHtml(o.title_zh||'')}"></label><label>${T()('description')} ID<textarea data-field="description">${window.ui.escapeHtml(o.description||'')}</textarea></label><label>${T()('description')} 中文<textarea data-field="description_zh">${window.ui.escapeHtml(o.description_zh||'')}</textarea></label><label>${T()('quarter')}<select data-field="quarter_key">${window.QuarterUtil.quarterOptions(window.QuarterUtil.getCurrentQuarter(),4).map(q=>`<option ${q===(o.quarter_key||window.QuarterUtil.getCurrentQuarter())?'selected':''}>${q}</option>`).join('')}</select></label><label>${T()('category')}<select data-field="category"><option>growth</option><option>operational_excellence</option><option>financial</option><option>team</option><option>product</option><option>marketing</option></select></label><label>${T()('owner')}<select data-field="owner_employee_id">${window.ui.employeeOptions(o.owner_employee_id,false)}</select></label><label>${T()('status')}<select data-field="status"><option>active</option><option>achieved</option><option>missed</option><option>cancelled</option></select></label></div>`; }
 function krForm(k={}){ const metrics=['lead_count','deal_count','total_revenue','net_income','total_marketing_spend','task_completion_rate','employee_count_active']; return `<div class="form-grid"><label>KR ID<input data-field="title" value="${window.ui.escapeHtml(k.title||'')}"></label><label>KR 中文<input data-field="title_zh" value="${window.ui.escapeHtml(k.title_zh||'')}"></label><label>Type<select data-field="type"><option ${k.type==='auto'?'selected':''}>auto</option><option ${k.type==='manual'?'selected':''}>manual</option></select></label><label>Module<select data-field="module"><option>operational</option><option>financial</option><option>marketing</option><option>management</option></select></label><label>Metric<select data-field="metric">${metrics.map(m=>`<option ${k.data_source?.metric===m?'selected':''}>${m}</option>`).join('')}</select></label><label>${T()('current')} manual<input data-field="manual_progress_value" type="number" value="${k.manual_progress_value??k.current_value??0}"></label><label>${T()('target')}<input data-field="target_value" type="number" value="${k.target_value||0}"></label><label>Unit<select data-field="unit"><option>count</option><option>leads</option><option>deals</option><option>rp</option><option>%</option></select></label><label>Weight<input data-field="weight" type="number" step="0.01" min="0" max="1" value="${k.weight||0.33}"></label><label>Notes<textarea data-field="notes">${window.ui.escapeHtml(k.notes||'')}</textarea></label></div>`; }
 function openOKR(id){ const o=window.storage.get('okrs',id)||{}; const isNew=!id; const krs=id?window.storage.list('krs',k=>k.okr_id===id):[]; const m=window.ui.modal(isNew?T()('new_okr'):T()('edit'), `<div class="tabs"><div class="tab-buttons"><button class="active" data-tab="info">Info</button><button data-tab="krs">KR</button></div><div data-tab-panel="info">${okrForm(o)}</div><div data-tab-panel="krs" class="hidden"><div id="modalKrList">${krs.map(k=>`<div class="list-item"><strong>${window.ui.escapeHtml(window.ui.titleFor(k))}</strong><button class="btn small" data-edit-kr="${k.id}">Edit KR</button><button class="btn danger small" data-del-kr="${k.id}">Delete</button></div>`).join('')||window.ui.empty('KR kosong')}</div><button class="btn primary" id="addKrBtn">+ KR</button></div></div>`, `<button class="btn" data-close>${T()('cancel')}</button><button class="btn primary" id="saveOkrBtn">${T()('save')}</button>`); window.ui.bindTabs(m.node); const form=m.node.querySelector('[data-tab-panel="info"]'); m.node.querySelector('[data-field="category"]').value=o.category||'growth'; m.node.querySelector('[data-field="status"]').value=o.status||'active'; m.node.querySelector('#saveOkrBtn').onclick=()=>{const d=window.ui.dataFrom(form); if(!d.title)return window.ui.toast('Title wajib'); if(isNew){ id=window.storage.add('okrs',d); } else window.storage.update('okrs',id,d); m.close(); render();}; m.node.querySelector('#addKrBtn').onclick=()=>openKR(null,id,m); m.node.querySelectorAll('[data-edit-kr]').forEach(b=>b.onclick=()=>openKR(b.dataset.editKr,id,m)); m.node.querySelectorAll('[data-del-kr]').forEach(b=>b.onclick=()=>{if(confirm('Delete KR?')){window.storage.remove('krs',b.dataset.delKr);m.close();openOKR(id);render();}}); }
 function openKR(id,okrId,parent){ const k=window.storage.get('krs',id)||{}; const m=window.ui.modal('Key Result', krForm(k), `<button class="btn" data-close>${T()('cancel')}</button><button class="btn primary" id="saveKrBtn">${T()('save')}</button>`); m.node.querySelector('[data-field="type"]').value=k.type||'manual'; m.node.querySelector('[data-field="module"]').value=k.data_source?.module||'operational'; m.node.querySelector('[data-field="unit"]').value=k.unit||'count'; m.node.querySelector('#saveKrBtn').onclick=()=>{const d=window.ui.dataFrom(m.node); const payload={okr_id:okrId,title:d.title,title_zh:d.title_zh,type:d.type,manual_progress_value:d.manual_progress_value,target_value:d.target_value,current_value:d.manual_progress_value,unit:d.unit,weight:Number(d.weight||0),notes:d.notes,data_source:{module:d.module,metric:d.metric,filter:{period:'current_quarter'},aggregation:'count'}}; if(id)window.storage.update('krs',id,payload); else window.storage.add('krs',payload); m.close(); parent?.close(); openOKR(okrId); render();}; }
 function useTemplate(){ const q=document.getElementById('quarterSelect')?.value||window.QuarterUtil.getCurrentQuarter(); const id=window.storage.add('okrs',{quarter_key:q,title:'Pertumbuhan Bisnis',title_zh:'业务增长',description:'Template OKR growth.',description_zh:'业务增长模板。',owner_employee_id:'emp_aydin',category:'growth',status:'active'}); window.storage.add('krs',{okr_id:id,title:'100 leads baru',title_zh:'100条新线索',type:'auto',data_source:{module:'operational',metric:'lead_count',filter:{period:'current_quarter'},aggregation:'count'},target_value:100,current_value:0,unit:'leads',weight:.5}); window.storage.add('krs',{okr_id:id,title:'20 deal baru',title_zh:'20笔新交易',type:'auto',data_source:{module:'operational',metric:'deal_count',filter:{period:'current_quarter'},aggregation:'count'},target_value:20,current_value:0,unit:'deals',weight:.5}); render(); }
 function init(){ const sel=document.getElementById('quarterSelect'); if(sel){ const cur=window.storage.getSettings().management?.active_quarter||window.QuarterUtil.getCurrentQuarter(); sel.innerHTML=window.QuarterUtil.quarterOptions(cur,4).map(q=>`<option ${q===cur?'selected':''}>${q}</option>`).join(''); sel.onchange=render;} document.getElementById('prevQuarter')?.addEventListener('click',()=>{sel.value=window.QuarterUtil.addQuarter(sel.value,-1);render();}); document.getElementById('nextQuarter')?.addEventListener('click',()=>{sel.value=window.QuarterUtil.addQuarter(sel.value,1);render();}); document.getElementById('newOkrBtn')?.addEventListener('click',()=>openOKR(null)); document.getElementById('useTemplateBtn')?.addEventListener('click',useTemplate); render(); }
 window.OKRPage={init,render,openOKR};
})();
