(function(){
  function entriesForAccount(accountId,start='',end=''){
    const acc=storage.get('coa',accountId); if(!acc) return {account:null,rows:[],opening:0,totalDebit:0,totalCredit:0,ending:0};
    let running=UI.num(acc.opening_balance); const rows=[]; let totalDebit=0,totalCredit=0;
    const entries=storage.list('journal').slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.journal_number).localeCompare(String(b.journal_number)));
    entries.forEach(e=>{ (e.lines||[]).filter(l=>l.account_id===accountId).forEach(l=>{ const delta=acc.normal_balance==='debit' ? UI.num(l.debit)-UI.num(l.credit) : UI.num(l.credit)-UI.num(l.debit); if(start && e.date<start){ running+=delta; return; } if(end && e.date>end) return; running+=delta; totalDebit+=UI.num(l.debit); totalCredit+=UI.num(l.credit); rows.push({entry:e,line:l,balance:running}); }); });
    const opening = rows.length ? rows[0].balance - (acc.normal_balance==='debit' ? UI.num(rows[0].line.debit)-UI.num(rows[0].line.credit) : UI.num(rows[0].line.credit)-UI.num(rows[0].line.debit)) : running;
    return {account:acc,rows,opening,totalDebit,totalCredit,ending:running};
  }
  function getAccountBalance(accountId, asOf='9999-12-31'){
    const acc=storage.get('coa',accountId); if(!acc) return 0; let bal=UI.num(acc.opening_balance); storage.list('journal').forEach(e=>{ if(e.date>asOf) return; (e.lines||[]).filter(l=>l.account_id===accountId).forEach(l=>{ bal += acc.normal_balance==='debit' ? UI.num(l.debit)-UI.num(l.credit) : UI.num(l.credit)-UI.num(l.debit); }); }); return bal;
  }
  function fillSelect(){ const sel=document.getElementById('ledgerAccount'); if(sel){ const current=sel.value || 'acc_11000'; sel.innerHTML=UI.accountOptions(current); sel.value=current; } }
  function kpi(label,value){ return `<div class="kpi-card"><span>${label}</span><strong>${value}</strong></div>`; }
  function render(){ const sel=document.getElementById('ledgerAccount'); if(!sel) return; const current=sel.value || 'acc_11000'; fillSelect(); const accountId=sel.value || current || storage.list('coa')[0]?.id; sel.value=accountId; const start=document.getElementById('ledgerStart').value; const end=document.getElementById('ledgerEnd').value; const data=entriesForAccount(accountId,start,end); const body=document.getElementById('ledgerTbody'); const foot=document.getElementById('ledgerTfoot'); const sum=document.getElementById('ledgerSummary'); body.innerHTML=data.rows.map(r=>`<tr><td>${r.entry.date}</td><td>${r.entry.journal_number}</td><td>${UI.esc(r.entry.doc_number||'')}</td><td>${UI.esc(r.entry.description)}</td><td>${UI.esc(r.entry.client_name||'')}</td><td class="right">${r.line.debit?UI.rp(r.line.debit):'-'}</td><td class="right">${r.line.credit?UI.rp(r.line.credit):'-'}</td><td class="right"><b>${UI.rp(r.balance)}</b></td></tr>`).join('') || `<tr><td colspan="8"><div class="empty-state">${i18n.t('no_mutation')}</div></td></tr>`; foot.innerHTML=`<tr class="report-row-total"><td colspan="5">${i18n.t('total')}</td><td class="right">${UI.rp(data.totalDebit)}</td><td class="right">${UI.rp(data.totalCredit)}</td><td class="right">${UI.rp(data.ending)}</td></tr>`; sum.innerHTML=[kpi(i18n.t('account'),UI.accountName(data.account)),kpi(i18n.t('beginning_balance'),UI.rp(data.opening)),kpi(i18n.t('total_debit'),UI.rp(data.totalDebit)),kpi(i18n.t('ending_balance'),UI.rp(data.ending))].join(''); }
  function exportCSV(){ const accountId=document.getElementById('ledgerAccount')?.value; const d=entriesForAccount(accountId,document.getElementById('ledgerStart').value,document.getElementById('ledgerEnd').value); const lines=[[i18n.t('col_date'),i18n.t('col_journal_no'),i18n.t('col_doc_no'),i18n.t('col_desc'),i18n.t('client'),i18n.t('debit'),i18n.t('credit'),i18n.t('col_running_balance')].join(',')]; d.rows.forEach(r=>lines.push([r.entry.date,r.entry.journal_number,r.entry.doc_number||'',`"${String(r.entry.description).replace(/"/g,'""')}"`,r.entry.client_name||'',r.line.debit,r.line.credit,r.balance].join(','))); UI.downloadText(`buku-besar-${d.account?.code||'akun'}.csv`,lines.join('\n'),'text/csv'); }
  function init(){ if(document.body.dataset.page!=='ledger') return; const m=storage.getSettings().finance?.active_period || UI.monthKey(); document.getElementById('ledgerStart').value=UI.monthStart(m); document.getElementById('ledgerEnd').value=UI.monthEnd(m); fillSelect(); ['ledgerAccount','ledgerStart','ledgerEnd'].forEach(id=>document.getElementById(id)?.addEventListener('input',render)); document.getElementById('applyLedger')?.addEventListener('click',render); document.getElementById('exportLedgerCsv')?.addEventListener('click',exportCSV); document.getElementById('exportLedgerPdf')?.addEventListener('click',()=>PDFExport.exportElement('ledgerPrintArea',i18n.t('ledger_title'))); document.addEventListener('language:changed',render); render(); }
  window.Ledger={entriesForAccount,getAccountBalance}; document.addEventListener('DOMContentLoaded',init);
})();
