(function(){
  function usedAccountIds(){ const ids=new Set(); storage.list('journal').forEach(e=>(e.lines||[]).forEach(l=>ids.add(l.account_id))); return ids; }
  function render(){ const body=document.getElementById('coaTbody'); if(!body) return; const used=usedAccountIds(); const accounts=storage.list('coa').sort((a,b)=>a.code.localeCompare(b.code)); body.innerHTML=accounts.map(a=>`<tr><td><input class="coa-check" type="checkbox" value="${a.id}"></td><td><b>${a.code}</b></td><td>${UI.esc(UI.accountName(a,false))}</td><td>${UI.esc(i18n.getLang()==='zh' ? (a.name_id||'') : (a.name_zh||''))}</td><td>${a.type}</td><td>${a.normal_balance}</td><td class="right">${UI.rp(a.opening_balance)}</td><td><div class="table-actions"><button class="icon-btn coa-edit" data-id="${a.id}">✎</button><button class="icon-btn row-delete coa-delete" data-id="${a.id}" ${used.has(a.id)?'disabled title="Akun sudah dipakai"':''}>🗑</button></div></td></tr>`).join(''); body.querySelectorAll('.coa-edit').forEach(b=>b.onclick=()=>openAccountModal(storage.get('coa',b.dataset.id))); body.querySelectorAll('.coa-delete').forEach(b=>b.onclick=()=>deleteAccount(b.dataset.id)); }
  function openAccountModal(acc=null){ const a=acc||{code:'',name_id:'',name_zh:'',type:'expense',subtype:'other',normal_balance:'debit',opening_balance:0,is_active:true}; const body=`<div class="form-grid"><label>Kode Akun<input id="aCode" value="${UI.esc(a.code)}"></label><label>Nama ID<input id="aNameId" value="${UI.esc(a.name_id)}"></label><label>Nama 中文<input id="aNameZh" value="${UI.esc(a.name_zh)}"></label><label>Tipe<select id="aType"><option value="asset">asset</option><option value="liability">liability</option><option value="equity">equity</option><option value="revenue">revenue</option><option value="expense">expense</option></select></label><label>Subtype<input id="aSubtype" value="${UI.esc(a.subtype||'')}"></label><label>Normal Balance<select id="aNormal"><option value="debit">debit</option><option value="credit">credit</option></select></label><label>Saldo Awal<input id="aOpening" type="number" value="${a.opening_balance||0}"></label><label>Aktif<select id="aActive"><option value="true">Ya</option><option value="false">Tidak</option></select></label></div>`; const m=UI.modal(acc?'Edit Akun':'Tambah Akun',body,`<button class="btn" data-close="1">Cancel</button><button class="btn primary" id="saveAccount">Save</button>`); m.querySelector('#aType').value=a.type; m.querySelector('#aNormal').value=a.normal_balance; m.querySelector('#aActive').value=String(a.is_active!==false); m.querySelector('#saveAccount').onclick=()=>{ const data={code:m.querySelector('#aCode').value.trim(),name_id:m.querySelector('#aNameId').value.trim(),name_zh:m.querySelector('#aNameZh').value.trim(),type:m.querySelector('#aType').value,subtype:m.querySelector('#aSubtype').value.trim(),normal_balance:m.querySelector('#aNormal').value,opening_balance:UI.num(m.querySelector('#aOpening').value),is_active:m.querySelector('#aActive').value==='true'}; if(!data.code||!data.name_id) return UI.toast('Kode dan nama wajib.'); const duplicate=storage.list('coa').find(x=>x.code===data.code && x.id!==a.id); if(duplicate) return UI.toast('Kode akun sudah ada.'); acc?storage.update('coa',acc.id,data):storage.add('coa',data); m.remove(); UI.toast('Akun tersimpan.'); render(); if(window.Journal) Journal.renderJournalPage(); }; }
  function deleteAccount(id){ if(usedAccountIds().has(id)) return UI.toast('Akun sudah dipakai di jurnal, tidak bisa dihapus.'); if(confirm('Hapus akun ini?')){ storage.remove('coa',id); render(); } }
  function bulkDelete(){ const ids=[...document.querySelectorAll('.coa-check:checked')].map(x=>x.value); const used=usedAccountIds(); const blocked=ids.filter(id=>used.has(id)); if(blocked.length) return UI.toast(`${blocked.length} akun sudah dipakai, tidak bisa bulk delete.`); if(ids.length && confirm(`Hapus ${ids.length} akun?`)){ storage.bulkRemove('coa',ids); render(); } }
  function init(){ if(document.body.dataset.page!=='jurnal') return; document.getElementById('addAccountBtn')?.addEventListener('click',()=>openAccountModal()); document.getElementById('bulkDeleteCoa')?.addEventListener('click',bulkDelete); document.getElementById('selectAllCoa')?.addEventListener('change',e=>document.querySelectorAll('.coa-check').forEach(c=>c.checked=e.target.checked)); document.addEventListener('language:changed',render); render(); }
  window.COA={render,openAccountModal}; document.addEventListener('DOMContentLoaded',init);
})();
