(function(){
  const dict = {
    id: {
      module_financial:'Financial Module', nav_dashboard:'Dashboard', nav_jurnal:'Jurnal', nav_ledger:'Buku Besar', nav_reports:'Laporan', role_label:'Role', export_json:'Export JSON', import_json:'Import JSON',
      access_denied_title:'Akses ditolak', access_denied_desc:'Role Sales/Marketing tidak punya akses ke Financial Module.',
      dashboard_eyebrow:'Kontrol accounting harian', dashboard_title:'Dashboard Financial', quick_manual_journal:'+ Jurnal Manual', quick_reports:'Lihat Laporan', quick_pdf_month:'Export PDF Bulan Ini', quick_import_cashflow:'Import OPS JSON', chart_rev_exp:'Pendapatan vs Beban 6 Bulan', chart_revenue_mix:'Komposisi Pendapatan', pending_entries:'Pending Journal Entries', review_all:'Review Semua', recent_journal:'Recent Journal Entries', view_all:'View All',
      jurnal_eyebrow:'Double-entry accounting', jurnal_title:'Jurnal Umum', add_manual_journal:'+ Tambah Jurnal Manual', review_pending_auto:'Review Pending Auto Entries', import_cashflow_ops:'Import dari OPS JSON', tab_journal:'Jurnal Umum', tab_coa:'COA Management', tab_settings:'Settings', filter_all_source:'Semua Sumber', delete_selected:'Delete Selected', col_date:'Tanggal', col_journal_no:'No Jurnal', col_doc_no:'No Doc', col_desc:'Keterangan', col_account:'Akun', coa_title:'Chart of Accounts', add_account:'+ Tambah Akun', settings_title:'Settings', language_label:'Bahasa', active_period:'Periode Aktif', save_settings:'Save Settings', reset_all:'Reset All Data',
      ledger_eyebrow:'General Ledger per akun', ledger_title:'Buku Besar', export_pdf_ledger:'Export PDF Buku Besar', export_csv:'Export CSV', apply_filter:'Apply', col_running_balance:'Saldo Running',
      reports_eyebrow:'TB, IS, BS, Cash Flow, Investor', reports_title:'Laporan Financial', print_view:'Print View', export_pdf:'Export PDF', export_pdf_multi:'Export PDF Multi-Bulan', tab_tb:'Trial Balance', tab_is:'Income Statement', tab_bs:'Balance Sheet', tab_cf:'Cash Flow', tab_investor:'Investor Report', as_of_date:'Sampai Tanggal', prev_month:'← Bulan Sebelumnya', next_month:'Bulan Berikutnya →', report_period:'Periode Laporan / 报告期',
      total_assets:'Total Aset', total_liabilities:'Total Liabilitas', total_equity:'Total Ekuitas', revenue_month:'Pendapatan Bulan Ini', expense_month:'Beban Bulan Ini', net_income_month:'Net Income Bulan Ini', cash_on_hand:'Cash on Hand',
      debit:'Debit', credit:'Kredit', client:'Client', ref:'Ref', proof:'Proof', action:'Action', code:'Kode', account_name:'Nama Akun', account_name_id:'Nama ID', account_name_zh:'Nama 中文', type:'Tipe', normal:'Normal', opening_balance:'Saldo Awal', all_accounts:'Semua Akun', no_mutation:'Tidak ada mutasi.', no_journal:'Belum ada jurnal.', no_pending:'Tidak ada pending entry dari Operational.', no_valid_row:'Tidak ada row valid.',
      account:'Akun', beginning_balance:'Saldo Awal', ending_balance:'Saldo Akhir', total:'Total', total_debit:'Total Debit', total_credit:'Total Kredit', balance:'BALANCE', not_balance:'TIDAK BALANCE', difference:'Selisih',
      trial_balance:'Trial Balance', income_statement:'Income Statement', balance_sheet:'Balance Sheet', cash_flow_statement:'Cash Flow Statement', revenue:'Pendapatan', expense:'Beban', assets:'Aset', liabilities_equity:'Liabilitas + Ekuitas', liabilities:'Liabilitas', equity:'Ekuitas', current_period_income:'Laba Periode Berjalan', total_liabilities_equity:'Total Liabilitas + Ekuitas', balance_check:'Balance Check Selisih', beginning_cash:'Saldo Kas Awal', operating_cash_flow:'Arus Kas Operasi', investing_cash_flow:'Arus Kas Investasi', financing_cash_flow:'Arus Kas Pendanaan', net_cash_flow:'Net Cash Flow', ending_cash:'Saldo Kas Akhir',
      investor_report:'Investor Report', section_position:'A. Ringkasan Posisi Keuangan', section_performance:'B. Kinerja Bulan Ini', section_comparison:'C. Perbandingan vs Bulan Lalu', section_cumulative:'D. Akumulasi Sejak Operasi', section_top_expenses:'E. Top 5 Pengeluaran Bulan Ini', section_notes:'F. Catatan', cash_available:'Kas Tersedia', capital_deployed:'Modal Deployed / Piutang', prepaid_expense:'Beban Dibayar Dimuka', fixed_assets:'Aset Tetap', seized_motor_inventory:'Inventory Motor Sitaan', revenue_fee_js:'Pendapatan Fee JS', revenue_fee_installment:'Pendapatan Fee Cicilan', revenue_margin_bridging:'Pendapatan Margin Jembatan', total_revenue:'Total Pendapatan', total_expense:'Total Beban', net_income:'Laba Bersih', net_margin:'Net Margin', cumulative_fee:'Total Fee Diterima', cumulative_expense:'Total Beban', cumulative_profit:'Laba Kumulatif', investor_capital_paid:'Modal Investor Disetor', investor_roi:'ROI Investor', amount:'Jumlah', printed:'Dicetak', notes_saved:'Catatan tersimpan.', confidential:'Confidential', internal_use:'Internal Use Only', report_title:'Nama Laporan', start_date:'Start', end_date:'End', employee:'Karyawan', employee_name:'Nama', wage:'Gaji', commission:'Komisi', base_salary:'Gaji Pokok', sales_tier:'Jenjang Sales', junior_sales:'Junior Sales', senior_sales:'Senior Sales', motor_sitaan:'Motor Sitaan', pending_commission:'Komisi Pending', pending_wage_actions:'Pending Wage Actions', motor_sitaan_pending_sale:'Motor Sitaan Pending Sale', approve_commission:'Approve Komisi', pay_commission:'Bayar Komisi', slip_gaji:'Slip Gaji', total_wage:'Total Gaji', margin_sitaan:'Margin Motor Sitaan', approved:'Approved', paid:'Paid'
    },
    zh: {
      module_financial:'财务模块', nav_dashboard:'仪表盘', nav_jurnal:'总日记账', nav_ledger:'总分类账', nav_reports:'财务报表', role_label:'角色', export_json:'导出JSON', import_json:'导入JSON',
      access_denied_title:'拒绝访问', access_denied_desc:'销售/营销角色不能访问财务模块。',
      dashboard_eyebrow:'每日会计控制', dashboard_title:'财务仪表盘', quick_manual_journal:'+ 手动凭证', quick_reports:'查看报表', quick_pdf_month:'导出本月PDF', quick_import_cashflow:'导入运营JSON', chart_rev_exp:'近6个月收入与费用', chart_revenue_mix:'收入结构', pending_entries:'待审核日记账', review_all:'全部审核', recent_journal:'最近日记账', view_all:'查看全部',
      jurnal_eyebrow:'复式记账', jurnal_title:'总日记账', add_manual_journal:'+ 新增手动凭证', review_pending_auto:'审核自动凭证', import_cashflow_ops:'从运营JSON导入', tab_journal:'总日记账', tab_coa:'会计科目', tab_settings:'设置', filter_all_source:'全部来源', delete_selected:'删除所选', col_date:'日期', col_journal_no:'凭证号', col_doc_no:'单据号', col_desc:'说明', col_account:'科目', coa_title:'会计科目表', add_account:'+ 新增科目', settings_title:'设置', language_label:'语言', active_period:'当前期间', save_settings:'保存设置', reset_all:'重置全部数据',
      ledger_eyebrow:'按科目查看总账', ledger_title:'总分类账', export_pdf_ledger:'导出总账PDF', export_csv:'导出CSV', apply_filter:'应用', col_running_balance:'累计余额',
      reports_eyebrow:'试算/损益/资产负债/现金流/投资人', reports_title:'财务报表', print_view:'打印视图', export_pdf:'导出PDF', export_pdf_multi:'导出多月PDF', tab_tb:'试算平衡表', tab_is:'损益表', tab_bs:'资产负债表', tab_cf:'现金流量表', tab_investor:'投资人报告', as_of_date:'截至日期', prev_month:'← 上个月', next_month:'下个月 →', report_period:'报告期',
      total_assets:'总资产', total_liabilities:'总负债', total_equity:'总权益', revenue_month:'本月收入', expense_month:'本月费用', net_income_month:'本月净利润', cash_on_hand:'可用现金',
      debit:'借方', credit:'贷方', client:'客户', ref:'参考', proof:'凭证', action:'操作', code:'科目代码', account_name:'科目名称', account_name_id:'印尼文名称', account_name_zh:'中文名称', type:'类型', normal:'余额方向', opening_balance:'期初余额', all_accounts:'全部科目', no_mutation:'没有发生额。', no_journal:'暂无日记账。', no_pending:'暂无来自运营模块的待审核凭证。', no_valid_row:'没有有效行。',
      account:'科目', beginning_balance:'期初余额', ending_balance:'期末余额', total:'合计', total_debit:'借方合计', total_credit:'贷方合计', balance:'平衡', not_balance:'不平衡', difference:'差额',
      trial_balance:'试算平衡表', income_statement:'损益表', balance_sheet:'资产负债表', cash_flow_statement:'现金流量表', revenue:'收入', expense:'费用', assets:'资产', liabilities_equity:'负债 + 权益', liabilities:'负债', equity:'权益', current_period_income:'本期利润', total_liabilities_equity:'负债和权益合计', balance_check:'平衡检查差额', beginning_cash:'期初现金余额', operating_cash_flow:'经营活动现金流', investing_cash_flow:'投资活动现金流', financing_cash_flow:'筹资活动现金流', net_cash_flow:'现金净流量', ending_cash:'期末现金余额',
      investor_report:'投资人报告', section_position:'A. 财务状况摘要', section_performance:'B. 本月经营业绩', section_comparison:'C. 与上月对比', section_cumulative:'D. 运营以来累计', section_top_expenses:'E. 本月前五大支出', section_notes:'F. 备注', cash_available:'可用现金', capital_deployed:'已投放资金 / 应收款', prepaid_expense:'预付费用', fixed_assets:'固定资产', seized_motor_inventory:'收回摩托车库存', revenue_fee_js:'临时买卖服务费收入', revenue_fee_installment:'分期服务费收入', revenue_margin_bridging:'过桥利润收入', total_revenue:'收入合计', total_expense:'费用合计', net_income:'净利润', net_margin:'净利率', cumulative_fee:'累计服务费收入', cumulative_expense:'累计费用', cumulative_profit:'累计利润', investor_capital_paid:'投资人实缴资本', investor_roi:'投资回报率', amount:'金额', printed:'打印日期', notes_saved:'备注已保存。', confidential:'机密', internal_use:'内部使用', report_title:'报表名称', start_date:'开始日期', end_date:'结束日期', employee:'员工', employee_name:'姓名', wage:'工资', commission:'佣金', base_salary:'基本工资', sales_tier:'销售级别', junior_sales:'初级销售', senior_sales:'高级销售', motor_sitaan:'扣押摩托', pending_commission:'待审佣金', pending_wage_actions:'工资待办事项', motor_sitaan_pending_sale:'待售扣押摩托', approve_commission:'批准佣金', pay_commission:'支付佣金', slip_gaji:'工资单', total_wage:'总工资', margin_sitaan:'扣押车销售毛利', approved:'已批准', paid:'已支付'
    }
  };
  function getLang(){ return (storage.getSettings().language || 'id'); }
  function humanize(key){ return String(key||'').split('.').pop().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
  function t(key,fallback){ const lang=getLang(); return (dict[lang] && dict[lang][key]) || dict.id[key] || fallback || humanize(key); }
  function apply(){ document.documentElement.lang=getLang(); document.querySelectorAll('[data-i18n]').forEach(el=>{ const k=el.dataset.i18n; if(t(k)) el.textContent=t(k); }); }
  function toggle(){ const next=getLang()==='id'?'zh':'id'; storage.saveSettings({language:next}); apply(); document.dispatchEvent(new CustomEvent('language:changed')); }
  window.i18n={dict,t,getLang,apply,toggle};
  document.addEventListener('DOMContentLoaded',apply);
})();
