(function(){
  let chartA=null, chartB=null, chartC=null;
  function monthFromUI(){ return document.getElementById('wageMonth')?.value || UI.monthKey(); }
  function commissionsFor(empId, month, statuses=['approved','paid']){ return storage.list('commissions').filter(c=>c.employee_id===empId && c.period_month===month && statuses.includes(c.status)); }
  function paidCommissions(empId, month){ return commissionsFor(empId, month, ['paid']); }
  function ensureWage(emp, month){
    let w=storage.list('wages').find(x=>x.employee_id===emp.id && x.period_month===month);
    if(!w){ const id=storage.add('wages',{employee_id:emp.id,period_month:month,base_salary:UI.num(emp.base_salary),commissions:[],total_commission:0,total_wage:UI.num(emp.base_salary),status:'draft',payment_date:null,payment_proof_link:'',journal_entry_id:null,notes:''}); w=storage.get('wages',id); }
    return refreshWageForEmployeeMonth(emp.id, month);
  }
  function generatePeriod(month=monthFromUI()){ storage.list('employees').filter(e=>e.status==='active').forEach(e=>ensureWage(e,month)); UI.toast('Wage period generated.'); renderWageTab(); }
  function refreshWageForEmployeeMonth(empId, month){
    const emp=storage.get('employees',empId); if(!emp) return null;
    let w=storage.list('wages').find(x=>x.employee_id===empId && x.period_month===month);
    if(!w){ const id=storage.add('wages',{employee_id:empId,period_month:month,base_salary:UI.num(emp.base_salary),commissions:[],total_commission:0,total_wage:UI.num(emp.base_salary),status:'draft',payment_date:null,payment_proof_link:'',journal_entry_id:null,notes:''}); w=storage.get('wages',id); }
    const paid=paidCommissions(empId,month); const totalCom=paid.reduce((a,c)=>a+UI.num(c.commission_amount),0);
    return storage.update('wages',w.id,{base_salary:UI.num(emp.base_salary),commissions:paid.map(c=>c.id),total_commission:totalCom,total_wage:UI.num(emp.base_salary)+totalCom});
  }
  function approveAll(month=monthFromUI()){ storage.list('commissions').filter(c=>c.period_month===month&&c.status==='pending').forEach(c=>Commission.approveCommission(c.id)); UI.toast('Pending commissions approved.'); renderWageTab(); }
  function payCommissionModal(id){ const c=storage.get('commissions',id); const emp=storage.get('employees',c.employee_id); const m=UI.modal(i18n.t('pay_commission'),`<p>${UI.esc(emp?.name||'-')} · ${UI.rp(c.commission_amount)}</p><div class="form-grid"><label>Payment Date<input id="payDate" type="date" value="${UI.dateToday()}"></label><label>Proof Link<input id="proofLink"></label></div>`,`<button class="btn" data-close="1">Cancel</button><button class="btn primary" id="confirmPay">Pay</button>`); m.querySelector('#confirmPay').onclick=()=>{ try{ Commission.payCommission(id,{payment_date:m.querySelector('#payDate').value,proof_link:m.querySelector('#proofLink').value}); m.remove(); UI.toast('Komisi dibayar.'); renderWageTab(); }catch(e){ UI.toast(e.message); } }; }
  function payWageModal(id){ const w=storage.get('wages',id); const emp=storage.get('employees',w.employee_id); const amount=UI.num(w.base_salary); const m=UI.modal('Pay Base Salary',`<p>${UI.esc(emp?.name||'-')} · ${UI.rp(amount)}</p><div class="form-grid"><label>Payment Date<input id="payDate" type="date" value="${UI.dateToday()}"></label><label>Proof Link<input id="proofLink"></label></div>`,`<button class="btn" data-close="1">Cancel</button><button class="btn primary" id="confirmPay">Pay</button>`); m.querySelector('#confirmPay').onclick=()=>{ try{ const entry=Journal.post({date:m.querySelector('#payDate').value,description:`Bayar gaji pokok ${emp?.name||''} ${w.period_month}`,client_name:emp?.name||'',doc_number:w.period_month,proof_link:m.querySelector('#proofLink').value,source:'wage_payment',lines:[line('54000',amount,0),line('11000',0,amount)]}); storage.update('wages',id,{status:'paid',payment_date:m.querySelector('#payDate').value,payment_proof_link:m.querySelector('#proofLink').value,journal_entry_id:entry.id}); m.remove(); UI.toast('Gaji pokok dibayar.'); renderWageTab(); }catch(e){UI.toast(e.message);} }; }
  function line(code,debit,credit){ const a=UI.accountByCode(code); return {account_id:a?.id||'',account_code:code,account_name_snapshot:a?.name_id||code,debit:UI.num(debit),credit:UI.num(credit)}; }
  function renderCommissionDetails(empId,month){ const rows=storage.list('commissions').filter(c=>c.employee_id===empId&&c.period_month===month); if(!rows.length) return '<div class="empty-state">Belum ada commission.</div>'; return `<table class="report-table"><thead><tr><th>Deal</th><th>Base</th><th>%</th><th>${i18n.t('commission')}</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${UI.esc(c.deal_id)}</td><td class="right">${UI.rp(c.base_amount)}</td><td class="right">${c.commission_pct}%</td><td class="right">${UI.rp(c.commission_amount)}</td><td>${UI.commissionBadge(c.status)}</td><td>${c.status==='pending'?`<button class="btn small approve-com" data-id="${c.id}">${i18n.t('approve_commission')}</button>`:''}${c.status==='approved'?`<button class="btn small primary pay-com" data-id="${c.id}">${i18n.t('pay_commission')}</button>`:''}</td></tr>`).join('')}</tbody></table>`; }
  function renderCharts(month){ if(!window.Chart) return; const months=[]; const now=new Date(month+'-01'); for(let i=5;i>=0;i--){ const d=new Date(now.getFullYear(), now.getMonth()-i, 1); months.push(d.toISOString().slice(0,7)); } const total=months.map(m=>storage.list('wages').filter(w=>w.period_month===m).reduce((a,w)=>a+UI.num(w.total_wage),0)); const base=months.map(m=>storage.list('wages').filter(w=>w.period_month===m).reduce((a,w)=>a+UI.num(w.base_salary),0)); const com=months.map(m=>storage.list('wages').filter(w=>w.period_month===m).reduce((a,w)=>a+UI.num(w.total_commission),0)); const ctx=document.getElementById('wageChart'); if(ctx){ chartA?.destroy(); chartA=new Chart(ctx,{type:'bar',data:{labels:months,datasets:[{label:i18n.t('total_wage'),data:total}]},options:{plugins:{legend:{position:'bottom'}}}}); } const ctx2=document.getElementById('wageStackChart'); if(ctx2){ chartB?.destroy(); chartB=new Chart(ctx2,{type:'bar',data:{labels:months,datasets:[{label:i18n.t('base_salary'),data:base},{label:i18n.t('commission'),data:com}]},options:{plugins:{legend:{position:'bottom'}},scales:{x:{stacked:true},y:{stacked:true}}}}); } const dist=storage.list('wages').filter(w=>w.period_month===month); const ctx3=document.getElementById('wagePieChart'); if(ctx3){ chartC?.destroy(); chartC=new Chart(ctx3,{type:'pie',data:{labels:dist.map(w=>UI.employeeName(w.employee_id)),datasets:[{data:dist.map(w=>w.total_wage)}]},options:{plugins:{legend:{position:'bottom'}}}}); } }
  function renderWageTab(){ const root=document.getElementById('wageTab'); if(!root) return; const month=monthFromUI(); storage.list('employees').filter(e=>e.status==='active').forEach(e=>refreshWageForEmployeeMonth(e.id,month)); const wages=storage.list('wages').filter(w=>w.period_month===month); const total=wages.reduce((a,w)=>a+UI.num(w.total_wage),0); const table=document.getElementById('wageTable'); if(table) table.innerHTML=`<table class="data-table"><thead><tr><th>${i18n.t('employee')}</th><th>Role</th><th>${i18n.t('base_salary')}</th><th>${i18n.t('commission')}</th><th>${i18n.t('total_wage')}</th><th>Status</th><th>Action</th></tr></thead><tbody>${wages.map(w=>{const e=storage.get('employees',w.employee_id)||{}; return `<tr><td><b>${UI.esc(e.name||'-')}</b></td><td>${UI.esc(e.role||'-')}</td><td class="right">${UI.rp(w.base_salary)}</td><td class="right">${UI.rp(w.total_commission)}</td><td class="right"><b>${UI.rp(w.total_wage)}</b></td><td>${UI.esc(w.status)}</td><td><button class="btn small pay-wage" data-id="${w.id}">Pay Base</button><button class="btn small slip-pdf" data-id="${w.id}">PDF Slip</button></td></tr><tr><td colspan="7">${renderCommissionDetails(w.employee_id,month)}</td></tr>`}).join('')||`<tr><td colspan="7"><div class="empty-state">Generate wage period dulu.</div></td></tr>`}</tbody><tfoot><tr><td colspan="4"><b>Total</b></td><td class="right"><b>${UI.rp(total)}</b></td><td colspan="2"></td></tr></tfoot></table>`;
    const pending=document.getElementById('pendingCommissionsList'); if(pending){ const rows=storage.list('commissions').filter(c=>c.status==='pending'); pending.innerHTML=rows.map(c=>`<div class="list-item"><strong>${UI.employeeName(c.employee_id)} — ${UI.rp(c.commission_amount)}</strong><small>${UI.esc(c.deal_id)} · ${UI.esc(c.trigger_event)} · ${UI.rp(c.base_amount)} × ${c.commission_pct}%</small><button class="btn small approve-com" data-id="${c.id}">${i18n.t('approve_commission')}</button></div>`).join('')||'<div class="empty-state">Tidak ada pending commission.</div>'; }
    root.querySelectorAll('.approve-com').forEach(b=>b.onclick=()=>{ Commission.approveCommission(b.dataset.id); renderWageTab(); });
    root.querySelectorAll('.pay-com').forEach(b=>b.onclick=()=>payCommissionModal(b.dataset.id));
    root.querySelectorAll('.pay-wage').forEach(b=>b.onclick=()=>payWageModal(b.dataset.id));
    root.querySelectorAll('.slip-pdf').forEach(b=>b.onclick=()=>PDFExport.exportSlipGaji(b.dataset.id));
    renderCharts(month);
  }
  function init(){ if(document.body.dataset.page!=='reports') return; const sel=document.getElementById('wageMonth'); if(sel){ const m=storage.getSettings().finance?.active_period||UI.monthKey(); const months=window.Report?.getAvailableMonths?.()||[m]; const all=[...new Set([...months,m,UI.monthKey()])].sort(); sel.innerHTML=all.map(x=>`<option value="${x}">${window.Report?.monthLabel?Report.monthLabel(x):x}</option>`).join(''); sel.value=all.includes(m)?m:all[0]; sel.onchange=renderWageTab; document.getElementById('wagePrevBtn').onclick=()=>{ if(sel.selectedIndex>0){ sel.selectedIndex--; renderWageTab(); } }; document.getElementById('wageNextBtn').onclick=()=>{ if(sel.selectedIndex<sel.options.length-1){ sel.selectedIndex++; renderWageTab(); } }; }
    document.getElementById('generateWageBtn')?.addEventListener('click',()=>generatePeriod()); document.getElementById('approveAllCommissionBtn')?.addEventListener('click',()=>approveAll()); document.getElementById('exportWagePdfBtn')?.addEventListener('click',()=>PDFExport.exportWageSummary(monthFromUI())); document.addEventListener('language:changed',renderWageTab); if(location.hash==='#wage') setTimeout(()=>document.querySelector('[data-tab="wageTab"]')?.click(),200); renderWageTab(); }
  window.Wage={generatePeriod,refreshWageForEmployeeMonth,approveAll,renderWageTab,payWageModal,payCommissionModal};
  document.addEventListener('DOMContentLoaded',init);
})();
