(function(){
 function arr(k){try{return JSON.parse(localStorage.getItem(k)||'[]')||[]}catch(e){return[]}}
 function operational(){return {leads:arr('otokita.leads'),deals:arr('otokita.deals')}}
 function financial(){return {journal:arr('otokita.journal'),coa:arr('otokita.coa'),commissions:arr('otokita.commissions'),wages:arr('otokita.wages'),motor_sitaan:arr('otokita.motor_sitaan')}}
 function marketing(){return {videos:arr('otokita.mkt_videos'),campaigns:arr('otokita.mkt_campaigns'),posters:arr('otokita.mkt_poster_batches'),partners:arr('otokita.mkt_partners'),assets:arr('otokita.mkt_assets')}}
 function management(){return {employees:arr('otokita.employees'),kpis:arr('otokita.kpis'),okrs:arr('otokita.okrs'),tasks:arr('otokita.tasks'),completions:arr('otokita.task_completions')}}
 function checkModuleAvailability(){return {operational:!!localStorage.getItem('otokita.deals')||!!localStorage.getItem('otokita.leads'),financial:!!localStorage.getItem('otokita.journal'),marketing:!!localStorage.getItem('otokita.mkt_videos')||!!localStorage.getItem('otokita.mkt_campaigns'),management:!!localStorage.getItem('otokita.management_initialized')}}
 function getEmployeeMetrics(employee_id){const m=management(),f=financial();const tasks=m.tasks.filter(t=>(t.assignee_employee_ids||[]).includes(employee_id));const completed=tasks.filter(t=>t.status==='completed').length;const comm=f.commissions.filter(c=>c.employee_id===employee_id);return {tasks_assigned:tasks.length,tasks_completed:completed,okr_completion:0,commission_earned:comm.reduce((a,c)=>a+Number(c.commission_amount||0),0),pending_commissions:comm.filter(c=>c.status==='pending').length};}
 window.ModuleBridge={getOperationalData:operational,getFinancialData:financial,getMarketingData:marketing,getManagementData:management,checkModuleAvailability,getEmployeeMetrics,operational:{getDeals:(fn)=>operational().deals.filter(fn||(()=>true)),getLeads:(fn)=>operational().leads.filter(fn||(()=>true))},financial:{getJournal:(fn)=>financial().journal.filter(fn||(()=>true)),getCoa:()=>financial().coa},marketing:{getVideos:(fn)=>marketing().videos.filter(fn||(()=>true))},management:{getEmployees:(fn)=>management().employees.filter(fn||(()=>true)),getKPIs:(fn)=>management().kpis.filter(fn||(()=>true)),getOKRs:(fn)=>management().okrs.filter(fn||(()=>true))},cross:{getEmployeeMetrics}};
})();
